---
title: Política editorial
sidebar: true
menu: 
  main: 
    name: Política editorial
    weight: 4
---

El Quantificador es un revista semestral publicada por el *Laboratorio de Investigación para el Desarrollo del Ecuador (LIDE)*. La revista incluye artículos de análisis y notas metodológicas, así como análisis de las últimas investigaciones en ciencias sociales.

El Quantificador está dirigido a personas interesadas en las tendencias sociales, el cambio social y las implicaciones del conocimiento social en las políticas y el debate público. Nuestros artículos permiten que la investigación social de vanguardia sea accesible para los lectores en general. Somos la cara pública de las ciencias sociales en Ecuador.

### El LIDE

El Laboratorio de Investigación para el Desarrollo del Ecuador (LIDE) es una ONG educativa ubicada en la ciudad de Guayaquil, Ecuador. El LIDE tiene como misión generar conocimiento científico en las áreas de las ciencias sociales y promover el uso de política pública basada en evidencia científica.

### Consejo editorial

*Editores en Jefe*

Luis Alonso Quijano Ruiz — Xiamen University, China  
Marco Faytong Haro — Pennsylvania State University, EEUU