---
title: 'Pruebas aleatorias de coronavirus: ¿cómo obtener estadísticas confiables para la toma decisiones?'
author: ''
date: '2020-04-13'
slug: pruebas-aleatorias-de-coronavirus-como-obtener-estadisticas-confiables-para-la-toma-decisiones-4
authors:
  - Alonso Quijano
categories:
  - Salud
tags:
  - Coronavirus
description: 'A partir del lunes 13 de abril se aplicará un semáforo que categorizará a las provincias de acuerdo al grado de contagio y de acuerdo a esto flexibilizar la cuarentena. Nos preguntamos, ¿con qué calidad de datos dispone el gobierno para tomar decisiones bien informadas? En este artículo discutimos el uso de pruebas aleatorias, un método que permite estimar el número real de contagios por provincia, cantón o parroquia.'
thumbnail: '/post/salud/2020-04-13-pruebas-aleatorias-de-coronavirus-como-obtener-estadisticas-confiables-para-la-toma-decisiones-4.jpeg'
images: 
  - "https://elquantificador.org/post/salud/2020-04-13-pruebas-aleatorias-de-coronavirus-como-obtener-estadisticas-confiables-para-la-toma-decisiones-4.jpeg"
---

```{r, include=FALSE}
# We load the libraries
library(tidyverse)
library(DT)

# We load the data to creathe the plots
# The global cases and test datasets are obtained from the Foundation for Innovative New Diagnostics (https://finddx.shinyapps.io/FIND_Cov_19_Tracker/)
global_cases_url <- "https://raw.githubusercontent.com/aquijanoruiz/elquantificador_posts/master/salud/2020-04-12-pruebas-aleatorias-de-coronavirus-como-obtener-estadisticas-confiables-para-la-toma-decisiones.Rmd/COVID19_GLOBAL_CASES.csv"
global_cases <- read_csv(global_cases_url)

global_tests_url <- "https://raw.githubusercontent.com/aquijanoruiz/elquantificador_posts/master/salud/2020-04-12-pruebas-aleatorias-de-coronavirus-como-obtener-estadisticas-confiables-para-la-toma-decisiones.Rmd/COVID19_GLOBAL_TESTS.csv"
global_tests <- read_csv(global_tests_url)

# The global deaths are obtained from the JHU database
global_deaths_url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
global_deaths <- read_csv(global_deaths_url)

today <- "2020-04-10"

# We take out the columns we won't need
global_cases <- global_cases %>% filter(date == today) %>% select(jhu_ID.x, alpha3, date, cases, population) %>% rename(country = jhu_ID.x)
global_tests <- global_tests %>% filter(date == today) %>% select(alpha3, tests_cumulative) 

# We tranform the global_deaths dataset from wide to long
global_deaths <- global_deaths %>% rename(country = `Country/Region`) %>% 
  select(-c(`Province/State`, Lat, Long)) %>%
  gather(date, deaths, - country) %>% 
  mutate(date = as.Date(date, format = "%m/%d/%y" )) %>% filter(date == today) %>% select(-date) %>%
  group_by(country) %>% summarize(deaths = sum(deaths))

# We join all the datasets
global <- global_cases %>% inner_join(global_tests, by = "alpha3") %>% left_join(global_deaths, by = "country") %>%
  mutate(cases_per_million = cases/population * 1e6,
         deaths_per_million = deaths/population * 1e6,
         test_per_million = tests_cumulative/population * 1e6,
         prevalence = cases/population)

# Coronavirus prevalence in Ecuador Vs Iceland
ecu_prev <- round((global %>% filter(alpha3 == "ECU"))$prevalence * 100,2)
isl_prev <- round((global %>% filter(alpha3 == "ISL"))$prevalence * 100, 1)
```

El jueves pasado la ministra María Paula Romo dio a conocer que a partir de hoy, lunes 13 de abril, se empezaría a implementar un semáforo de colores rojo, naranja y verde que limitará o permitirá la movilización y actividades. La pregunta que nos hacemos es ¿con qué calidad de información (estadística) el gobierno tomará la decisión de flexibilizar la cuarentena en ciertas provincias, ciudades o sectores? En este artículo presentaré una solución viable que, de aplicar rigurosidad científica, permitirá recolectar estadísticas más confiables. Estoy hablando de las pruebas aleatorias utilizadas en estudios de prevalencia, las cuales consisten en tomar una muestra significativa de individuos y realizar pruebas a modo de “lotería".

Ciertamente, la capacidad de las autoridades de realizar pruebas es mucho más baja que la de otros países, lo cual genera menor calidad de datos. Mientras Alemania ha logrado hacer más de 1.3 millones de pruebas, en Ecuador el número de pruebas a penas supera los 20 mil. La actual cifra de casos confirmados (que ya ha alcanzado los siete mil) excluye aquellos contagiados que no han logrado acceder a una prueba habiendo presentado síntomas, aquellos que no presentan síntomas y, por ende, aún desconocen que portan la enfermedad, e incluso aquellos que habiendo presentado síntomas no se han acercado a pedir una prueba ya sea por desconocimiento, temor o falta de recursos.

Dicho lo anterior, creo que dejo claro por qué me preocupa la capacidad del gobierno de tomar decisiones bien informadas con la calidad de datos que dispone. Estoy de acuerdo en que no sencillo estimar cuánto es el número real de contagios en el país. Sin embargo, la decisión de flexibilizar la cuarentena a través del mencionado semáforo debería depender, al menos, de un indicador confiable dos variables: el porcentaje actual (real) de contagios y el número de nuevos contagios que se vayan generando periódicamente. En epidemiología al primero se lo conoce como prevalencia y al segundo como incidencia. 


El desafío se encuentra en hallar este indicador de prevalencia e incidencia. Si usáramos cifras oficiales dividimos el número actual de casos confirmados para el total de población, obtenemos una prevalencia de `r ecu_prev`%. Es decir, `r ecu_prev`% de la población ecuatoriana estaría contagiada. Esta cifra es muy poco realista e incluso ingenua, tomando en cuenta que Islandia, país que ha sido elogiado por su éxito en realizar pruebas a casi la mitad de su población y capacidad de controlar la pandemia, tiene una prevalencia de `r isl_prev`%, o `r round(isl_prev/ecu_prev)` veces mayor a la de Ecuador.

Una mejor alternativa a las cifras disponibles (que ya he mencionado subestiman el número real de contagios) es un estudio de prevalencia a través de pruebas aleatorias. Un estudio de prevalencia consiste en obtener una muestra aleatoria de individuos en una determinada provincia, ciudad o parroquia (dependiendo de la unidad donde se quiera medir el porcentaje de contagio) y realizar pruebas de coronavirus. Gracias a la aleatorización, podemos asegurarnos que la probabilidad de escoger a un contagiado sintomático sea la misma a la de un contagiado asintomático o un no contagiado. De esta forma, podremos utilizar los resultados obtenidos por medio de la muestra para inferir sobre la población.

Hasta la fecha, son muy pocos los países que están realizando pruebas aleatorias a sus habitantes. Australia ha empezado a realizar pruebas aleatorias a medida que la demanda de pruebas iba disminuyendo. España ya anunció que va a hacer lo mismo. Por su parte, el gobierno ecuatoriano acaba de anunciar que está ampliando su capacidad de realizar pruebas. El alcalde de Quito, Jorge Yunda, también anunció la adquisición de 200 mil pruebas PCR de coronavirus para la capital. Tal parece, poco a poco es más factible la idea de empezar a realizar pruebas aleatorias. Para calcular el tamaño de la muestra se necesitan considerar variar variables, como el tamaño de la población que se va a estimar y el porcentaje esperado de contagio. En una pronta entrega, detallaré la metodología para calcular un adecuado tamaño de muestra.

Creo que, como todo ecuatoriano, deseo que las autoridades gubernamentales tomen las mejores decisiones y así asegurar la salud de todos los ecuatorianos. Una mala decisión podría costarles la vida a más personas y eso es lo que debemos evitar. Por esto, realizo las siguientes recomendaciones:

1.	No declarar a ninguna provincia en “naranja” o “verde” sin antes realizar pruebas aleatorias utilizando a la provincia como unidad de muestreo.
2.	En el caso de cantones con altos índices de contagio como Guayaquil, Samborondón y Daule deberán realizarse pruebas aleatorias utilizando estos cantones como unidad de muestreo para generar una estimación más precisa. Yo recomendaría incluso utilizar las parroquias como unidad de muestreo para entender a detalle el grado de contagio por diferentes sectores dentro de un cantón.
3.	Dado que las pruebas son escasas, las pruebas aleatorias deberían utilizarse cuando la demanda de pruebas empiece a disminuir. En aquellas provincias o cantones donde la demanda ya ha disminuido, podrían ya realizarse pruebas aleatorias para determinar el porcentaje exacto de contagio (prevalencia).
4.	Periódicamente se deberá medir los nuevos contagios (incidencia). En Singapur, Japón y Hong Kong se están reportando nuevos casos después de haber considerado la pandemia ya “controlada”. Por lo menos cada dos semanas, se deberán realizar pruebas aleatorias para calcular la incidencia de la enfermedad. De hallarse un nuevo brote de coronavirus, las autoridades deberán considerar retomar la cuarentena.

Espero que esta solución sea considerada por las autoridades y que quienes estén de acuerdo también puedan compartir para presionar a los hacedores de política pública a que tomen decisiones basándose en estadísticas libre de sesgos.